server:
  port: 8011
spring:
  application:
    name: geoprovider
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Xujianzheng1996
    url: jdbc:mysql://localhost:3306/geomap?serverTimezone=UTC
    hikari:
      maximum-pool-size: 20